function carList(){
  return[
    {
      name: 'Smart EQ fortwo coupe',
      range: 60,
      rapid: 'no',
      price: 19200,
      img: 'https://ev-database.uk/img/auto/Smart_fortwo_2020/Smart_fortwo_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1230/Smart-EQ-fortwo-coupe',
    },
    {
      name: 'Smart EQ forfour',
      range: 55,
      rapid: 'no',
      price: 19795,
      img: 'https://ev-database.uk/img/auto/Smart_forfour_2020/Smart_forfour_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1232/Smart-EQ-forfour',
    },
    {
      name: 'Fiat 500e Hatchback 24kWh',
      range: 100,
      rapid: 'yes',
      price: 20495,
      img: 'https://ev-database.uk/img/auto/Fiat_500e_Hatchback_2020/Fiat_500e_Hatchback_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1327/Fiat-500e-Hatchback-24-kWh',
    },
    {
      name: 'Smart EQ fortwo cabrio',
      range: 60,
      rapid: 'no',
      price: 21620,
      img: 'https://ev-database.uk/img/auto/Smart_cabrio_2020/Smart_cabrio_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1231/Smart-EQ-fortwo-cabrio',
    },
    {
      name: 'MG MG5 EV',
      range: 180,
      rapid: 'yes',
      price: 25095,
      img: 'https://ev-database.uk/img/auto/MG_MG5_EV/MG_MG5_EV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1313/MG-MG5-EV',
    },
    {
      name: 'Fiat 500e Hatchback 42kWh',
      range: 155,
      rapid: 'yes',
      price: 23995,
      img: 'https://ev-database.uk/img/auto/Fiat_500e_Hatchback_2020/Fiat_500e_Hatchback_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1285/Fiat-500e-Hatchback-42-kWh',
    },
    {
      name: 'MG ZS EV',
      range: 135,
      rapid: 'yes',
      price: 25995,
      img: 'https://ev-database.uk/img/auto/MG_ZS_EV/MG_ZS_EV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1201/MG-ZS-EV',
    },
    {
      name: 'Nissan Leaf',
      range: 135,
      rapid: 'yes',
      price: 25995,
      img: 'https://ev-database.uk/img/auto/Nissan_Leaf_2018/Nissan_Leaf_2018-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1106/Nissan-Leaf',
    },
    {
      name: 'Mini Electric',
      range: 115,
      rapid: 'yes',
      price: 26000,
      img: 'https://ev-database.uk/img/auto/Mini_Electric_2021/Mini_Electric_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1409/Mini-Electric',
    },
    {
      name: 'Mazda MX-30',
      range: 105,
      rapid: 'yes',
      price: 26045,
      img: 'https://ev-database.uk/img/auto/Mazda_MX-30/Mazda_MX-30-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1241/Mazda-MX-30',
    },
    {
      name: 'MG MG5 EV Long Range',
      range: 210,
      rapid: 'yes',
      price: 26495,
      img: 'https://ev-database.uk/img/auto/MG_MG5_EV/MG_MG5_EV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1526/MG-MG5-EV-Long-Range',
    },
    {
      name: 'Fiat 500e Cabrio',
      range: 150,
      rapid: 'yes',
      price: 26645,
      img: 'https://ev-database.uk/img/auto/Fiat_500e_Convertible_2020/Fiat_500e_Convertible_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1275/Fiat-500e-Cabrio',
    },
    {
      name: 'Renault Zoe ZE50 R110',
      range: 195,
      rapid: 'yes',
      price: 26795,
      img: 'https://ev-database.uk/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1164/Renault-Zoe-ZE50-R110',
    },
    {
      name: 'Volkswagen ID.3 Pure Performance',
      range: 170,
      rapid: 'yes',
      price: 27120,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID3/Volkswagen_ID3-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1127/Volkswagen-ID3-Pure-Performance',
    },
    {
      name: 'Vauxhall Corsa-e',
      range: 170,
      rapid: 'yes',
      price: 27140,
      img: 'https://ev-database.uk/img/auto/Opel_Corsa-e/Opel_Corsa-e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1192/Vauxhall-Corsa-e',
    },
    {
      name: 'Peugeot e-208',
      range: 170,
      rapid: 'yes',
      price: 27225,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-208_GT/Peugeot_e-208_GT-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1168/Peugeot-e-208',
    },
    {
      name: 'Honda e',
      range: 105,
      rapid: 'yes',
      price: 27660,
      img: 'https://ev-database.uk/img/auto/Honda_e/Honda_e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1171/Honda-e',
    },
    {
      name: 'Hyundai Kona Elecric 39 kWh',
      range: 155,
      rapid: 'yes',
      price: 27950,
      img: 'https://ev-database.uk/img/auto/Hyundai_Kona_Electric_2021/Hyundai_Kona_Electric_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1422/Hyundai-Kona-Electric-39-kWh',
    },
    {
      name: 'Volkswagen ID.3 Pro',
      range: 215,
      rapid: 'yes',
      price: 28420,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID3/Volkswagen_ID3-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1202/Volkswagen-ID3-Pro',
    },
    {
      name: 'CUPRA Born 110kWh-55kWh (coming 2022)',
      range: 170,
      rapid: 'yes',
      price: 28500,
      img: 'https://ev-database.uk/img/auto/Cupra_el-Born/Cupra_el-Born-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1178/CUPRA-Born-110-kW---55-kWh',
    },
    {
      name: 'Renault Zoe ZE50 R135',
      range: 190,
      rapid: 'yes',
      price: 28795,
      img: 'https://ev-database.uk/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1205/Renault-Zoe-ZE50-R135',
    },
    {
      name: 'Volkswagen ID.3 Pro Performance',
      range: 215,
      rapid: 'yes',
      price: 29740,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID3/Volkswagen_ID3-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1306/Volkswagen-ID3-Pro-Performance',
    },
    {
      name: 'Honda e Advance',
      range: 105,
      rapid: 'yes',
      price: 30160,
      img: 'https://ev-database.uk/img/auto/Honda_e/Honda_e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1233/Honda-e-Advance',
    },
    {
      name: 'Nissane e-NV200 Combi',
      range: 115,
      rapid: 'yes',
      price: 30255,
      img: 'https://ev-database.uk/img/auto/Nissan_e-NV200_Evalia_2018/Nissan_e-NV200_Evalia_2018-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1117/Nissan-e-NV200-Combi',
    },
    {
      name: 'Kia e-Nero 39kWh',
      range: 145,
      rapid: 'yes',
      price: 30345,
      img: 'https://ev-database.uk/img/auto/Kia_e-Niro-2020/Kia_e-Niro-2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1339/Kia-e-Niro-39-kWh',
    },
    {
      name: 'Peugeot e-Rifter Standard 50kWh (coming soon)',
      range: 120,
      rapid: 'yes',
      price: 30375,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-Rifter/Peugeot_e-Rifter-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1522/Peugeot-e-Rifter-Standard-50-kWh',
    },
    {
      name: 'Nissan Leaf e+',
      range: 200,
      rapid: 'yes',
      price: 30445,
      img: 'https://ev-database.uk/img/auto/Nissan_Leaf_2018/Nissan_Leaf_2018-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1144/Nissan-Leaf-eplus',
    },
    {
      name: 'CUPRA Born 150kWh-60kWh (coming 2022)',
      range: 215,
      rapid: 'yes',
      price: 30500,
      img: 'https://ev-database.uk/img/auto/Cupra_el-Born/Cupra_el-Born-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1516/CUPRA-Born-150-kW---62-kWh',
    },
    {
      name: 'Vauxhall Mokka-e',
      range: 155,
      rapid: 'yes',
      price: 30540,
      img: 'https://ev-database.uk/img/auto/Opel_Mokka-e/Opel_Mokka-e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1278/Vauxhall-Mokka-e',
    },
    {
      name: 'Hyundai IONIQ Electric',
      range: 155,
      rapid: 'yes',
      price: 30550,
      img: 'https://ev-database.uk/img/auto/Hyundai_IONIQ_Electric_2020/Hyundai_IONIQ_Electric_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1165/Hyundai-IONIQ-Electric',
    },
    {
      name: 'Peugeot e-2008 SUV',
      range: 155,
      rapid: 'yes',
      price: 30730,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-2008_SUV/Peugeot_e-2008_SUV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1206/Peugeot-e-2008-SUV',
    },
    {
      name: 'Citreon e-C4',
      range: 155,
      rapid: 'yes',
      price: 30895,
      img: 'https://ev-database.uk/img/auto/Citroen_e-C4/Citroen_e-C4-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1286/Citroen-e-C4',
    },
    {
      name: 'BMW i3 120 Ah',
      range: 145,
      rapid: 'yes',
      price: 31305,
      img: 'https://ev-database.uk/img/auto/BMW_i3_2019/BMW_i3_2019-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1145/BMW-i3-120-Ah',
    },
    {
      name: 'DS 3 Crossback E-Tense',
      range: 155,
      rapid: 'yes',
      price: 31500,
      img: 'https://ev-database.uk/img/auto/DS_3_Crossback/DS_3_Crossback-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1148/DS-3-Crossback-E-Tense',
    },
    {
      name: 'CUPRA Born 170kWh-62kWh (coming 2022)',
      range: 215,
      rapid: 'yes',
      price: 31500,
      img: 'https://ev-database.uk/img/auto/Cupra_el-Born/Cupra_el-Born-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1517/CUPRA-Born-170-kW---62-kWh',
    },
    {
      name: 'Renault Kangoo Crew Van ZE33',
      range: 100,
      rapid: 'no',
      price: 31680,
      img: 'https://ev-database.uk/img/auto/Renault_Kangoo_Maxi_ZE33/Renault_Kangoo_Maxi_ZE33-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1101/Renault-Kangoo-Crew-Van-ZE33',
    },
  ];
}

export default carList;
