function carList(){
  return[
    {
      name: 'Smart EQ fortwo coupe',
      range: 60,
      rapid: 'no',
      price: 19200,
      img: 'https://ev-database.uk/img/auto/Smart_fortwo_2020/Smart_fortwo_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1230/Smart-EQ-fortwo-coupe',
    },
    {
      name: 'Smart EQ forfour',
      range: 55,
      rapid: 'no',
      price: 19795,
      img: 'https://ev-database.uk/img/auto/Smart_forfour_2020/Smart_forfour_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1232/Smart-EQ-forfour',
    },
    {
      name: 'Fiat 500e Hatchback 24kWh',
      range: 100,
      rapid: 'yes',
      price: 20495,
      img: 'https://ev-database.uk/img/auto/Fiat_500e_Hatchback_2020/Fiat_500e_Hatchback_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1327/Fiat-500e-Hatchback-24-kWh',
    },
    {
      name: 'Smart EQ fortwo cabrio',
      range: 60,
      rapid: 'no',
      price: 21620,
      img: 'https://ev-database.uk/img/auto/Smart_cabrio_2020/Smart_cabrio_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1231/Smart-EQ-fortwo-cabrio',
    },
    {
      name: 'MG MG5 EV',
      range: 180,
      rapid: 'yes',
      price: 25095,
      img: 'https://ev-database.uk/img/auto/MG_MG5_EV/MG_MG5_EV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1313/MG-MG5-EV',
    },
    {
      name: 'Fiat 500e Hatchback 42kWh',
      range: 155,
      rapid: 'yes',
      price: 23995,
      img: 'https://ev-database.uk/img/auto/Fiat_500e_Hatchback_2020/Fiat_500e_Hatchback_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1285/Fiat-500e-Hatchback-42-kWh',
    },
    {
      name: 'MG ZS EV',
      range: 135,
      rapid: 'yes',
      price: 25995,
      img: 'https://ev-database.uk/img/auto/MG_ZS_EV/MG_ZS_EV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1201/MG-ZS-EV',
    },
    {
      name: 'Nissan Leaf',
      range: 135,
      rapid: 'yes',
      price: 25995,
      img: 'https://ev-database.uk/img/auto/Nissan_Leaf_2018/Nissan_Leaf_2018-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1106/Nissan-Leaf',
    },
    {
      name: 'Mini Electric',
      range: 115,
      rapid: 'yes',
      price: 26000,
      img: 'https://ev-database.uk/img/auto/Mini_Electric_2021/Mini_Electric_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1409/Mini-Electric',
    },
    {
      name: 'Mazda MX-30',
      range: 105,
      rapid: 'yes',
      price: 26045,
      img: 'https://ev-database.uk/img/auto/Mazda_MX-30/Mazda_MX-30-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1241/Mazda-MX-30',
    },
    {
      name: 'MG MG5 EV Long Range',
      range: 210,
      rapid: 'yes',
      price: 26495,
      img: 'https://ev-database.uk/img/auto/MG_MG5_EV/MG_MG5_EV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1526/MG-MG5-EV-Long-Range',
    },
    {
      name: 'Fiat 500e Cabrio',
      range: 150,
      rapid: 'yes',
      price: 26645,
      img: 'https://ev-database.uk/img/auto/Fiat_500e_Convertible_2020/Fiat_500e_Convertible_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1275/Fiat-500e-Cabrio',
    },
    {
      name: 'Renault Zoe ZE50 R110',
      range: 195,
      rapid: 'yes',
      price: 26795,
      img: 'https://ev-database.uk/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1164/Renault-Zoe-ZE50-R110',
    },
    {
      name: 'Volkswagen ID.3 Pure Performance',
      range: 170,
      rapid: 'yes',
      price: 27120,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID3/Volkswagen_ID3-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1127/Volkswagen-ID3-Pure-Performance',
    },
    {
      name: 'Vauxhall Corsa-e',
      range: 170,
      rapid: 'yes',
      price: 27140,
      img: 'https://ev-database.uk/img/auto/Opel_Corsa-e/Opel_Corsa-e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1192/Vauxhall-Corsa-e',
    },
    {
      name: 'Peugeot e-208',
      range: 170,
      rapid: 'yes',
      price: 27225,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-208_GT/Peugeot_e-208_GT-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1168/Peugeot-e-208',
    },
    {
      name: 'Honda e',
      range: 105,
      rapid: 'yes',
      price: 27660,
      img: 'https://ev-database.uk/img/auto/Honda_e/Honda_e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1171/Honda-e',
    },
    {
      name: 'Hyundai Kona Elecric 39 kWh',
      range: 155,
      rapid: 'yes',
      price: 27950,
      img: 'https://ev-database.uk/img/auto/Hyundai_Kona_Electric_2021/Hyundai_Kona_Electric_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1422/Hyundai-Kona-Electric-39-kWh',
    },
    {
      name: 'Volkswagen ID.3 Pro',
      range: 215,
      rapid: 'yes',
      price: 28420,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID3/Volkswagen_ID3-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1202/Volkswagen-ID3-Pro',
    },
    {
      name: 'CUPRA Born 110kWh-55kWh (coming 2022)',
      range: 170,
      rapid: 'yes',
      price: 28500,
      img: 'https://ev-database.uk/img/auto/Cupra_el-Born/Cupra_el-Born-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1178/CUPRA-Born-110-kW---55-kWh',
    },
    {
      name: 'Renault Zoe ZE50 R135',
      range: 190,
      rapid: 'yes',
      price: 28795,
      img: 'https://ev-database.uk/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1205/Renault-Zoe-ZE50-R135',
    },
    {
      name: 'Volkswagen ID.3 Pro Performance',
      range: 215,
      rapid: 'yes',
      price: 29740,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID3/Volkswagen_ID3-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1306/Volkswagen-ID3-Pro-Performance',
    },
    {
      name: 'Honda e Advance',
      range: 105,
      rapid: 'yes',
      price: 30160,
      img: 'https://ev-database.uk/img/auto/Honda_e/Honda_e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1233/Honda-e-Advance',
    },
    {
      name: 'Nissane e-NV200 Combi',
      range: 115,
      rapid: 'yes',
      price: 30255,
      img: 'https://ev-database.uk/img/auto/Nissan_e-NV200_Evalia_2018/Nissan_e-NV200_Evalia_2018-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1117/Nissan-e-NV200-Combi',
    },
    {
      name: 'Kia e-Nero 39kWh',
      range: 145,
      rapid: 'yes',
      price: 30345,
      img: 'https://ev-database.uk/img/auto/Kia_e-Niro-2020/Kia_e-Niro-2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1339/Kia-e-Niro-39-kWh',
    },
    {
      name: 'Peugeot e-Rifter Standard 50kWh (coming soon)',
      range: 120,
      rapid: 'yes',
      price: 30375,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-Rifter/Peugeot_e-Rifter-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1522/Peugeot-e-Rifter-Standard-50-kWh',
    },
    {
      name: 'Nissan Leaf e+',
      range: 200,
      rapid: 'yes',
      price: 30445,
      img: 'https://ev-database.uk/img/auto/Nissan_Leaf_2018/Nissan_Leaf_2018-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1144/Nissan-Leaf-eplus',
    },
    {
      name: 'CUPRA Born 150kWh-60kWh (coming 2022)',
      range: 215,
      rapid: 'yes',
      price: 30500,
      img: 'https://ev-database.uk/img/auto/Cupra_el-Born/Cupra_el-Born-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1516/CUPRA-Born-150-kW---62-kWh',
    },
    {
      name: 'Vauxhall Mokka-e',
      range: 155,
      rapid: 'yes',
      price: 30540,
      img: 'https://ev-database.uk/img/auto/Opel_Mokka-e/Opel_Mokka-e-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1278/Vauxhall-Mokka-e',
    },
    {
      name: 'Hyundai IONIQ Electric',
      range: 155,
      rapid: 'yes',
      price: 30550,
      img: 'https://ev-database.uk/img/auto/Hyundai_IONIQ_Electric_2020/Hyundai_IONIQ_Electric_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1165/Hyundai-IONIQ-Electric',
    },
    {
      name: 'Peugeot e-2008 SUV',
      range: 155,
      rapid: 'yes',
      price: 30730,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-2008_SUV/Peugeot_e-2008_SUV-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1206/Peugeot-e-2008-SUV',
    },
    {
      name: 'Citreon e-C4',
      range: 155,
      rapid: 'yes',
      price: 30895,
      img: 'https://ev-database.uk/img/auto/Citroen_e-C4/Citroen_e-C4-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1286/Citroen-e-C4',
    },
    {
      name: 'BMW i3 120 Ah',
      range: 145,
      rapid: 'yes',
      price: 31305,
      img: 'https://ev-database.uk/img/auto/BMW_i3_2019/BMW_i3_2019-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1145/BMW-i3-120-Ah',
    },
    {
      name: 'DS 3 Crossback E-Tense',
      range: 155,
      rapid: 'yes',
      price: 31500,
      img: 'https://ev-database.uk/img/auto/DS_3_Crossback/DS_3_Crossback-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1148/DS-3-Crossback-E-Tense',
    },
    {
      name: 'CUPRA Born 170kWh-62kWh (coming 2022)',
      range: 215,
      rapid: 'yes',
      price: 31500,
      img: 'https://ev-database.uk/img/auto/Cupra_el-Born/Cupra_el-Born-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1517/CUPRA-Born-170-kW---62-kWh',
    },
    {
      name: 'Renault Kangoo Crew Van ZE33',
      range: 100,
      rapid: 'no',
      price: 31680,
      img: 'https://ev-database.uk/img/auto/Renault_Kangoo_Maxi_ZE33/Renault_Kangoo_Maxi_ZE33-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1101/Renault-Kangoo-Crew-Van-ZE33',
    },
    {
      name: 'Citreon e-SpaceTourer M 50kWh',
      range: 115,
      rapid: 'yes',
      price: 31995,
      img: 'https://ev-database.uk/img/auto/Citroen_e-SpaceTourer/Citroen_e-SpaceTourer-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1341/Citroen-e-SpaceTourer-M-50-kWh',
    },
    {
      name: 'Skoda Enyaq iV 60',
      range: 205,
      rapid: 'yes',
      price: 31995,
      img: 'https://ev-database.uk/img/auto/Skoda_Enyaq_iV_2020/Skoda_Enyaq_iV_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1279/Skoda-Enyaq-iV-60',
    },
    {
      name: 'Volkwagen ID.4 Pure',
      range: 175,
      rapid: 'yes',
      price: 32150,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID4/Volkswagen_ID4-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1489/Volkswagen-ID4-Pure',
    },
    {
      name: 'BMW i3s 12 Ah',
      range: 140,
      rapid: 'yes',
      price: 32305,
      img: 'https://ev-database.uk/img/auto/BMW_i3_2019/BMW_i3_2019-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1149/BMW-i3s-120-Ah',
    },
    {
      name: 'Kia e-Nero 64kWh',
      range: 230,
      rapid: 'yes',
      price: 32445,
      img: 'https://ev-database.uk/img/auto/Kia_e-Niro-2020/Kia_e-Niro-2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1338/Kia-e-Niro-64-kWh',
    },
    {
      name: 'Peugeot e-Rifter Long 50 kWh (coming soon)',
      range: 120,
      rapid: 'yes',
      price: 32455,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-Rifter/Peugeot_e-Rifter-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1523/Peugeot-e-Rifter-Long-50-kWh',
    },
    {
      name: 'Renault Megane E-Tech Electric (from 2022)',
      range: 210,
      rapid: 'yes',
      price: 32500,
      img: 'https://ev-database.uk/img/auto/Renault_Megane_ETech/Renault_Megane_ETech-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1521/Renault-Megane-E-Tech-Electric',
    },
    {
      name: 'Hyundai Kona Electric 64kWh',
      range: 245,
      rapid: 'yes',
      price: 32550,
      img: 'https://ev-database.uk/img/auto/Hyundai_Kona_Electric_2021/Hyundai_Kona_Electric_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1423/Hyundai-Kona-Electric-64-kWh',
    },
    {
      name: 'Volkwagen ID.4 Pure Performance',
      range: 175,
      rapid: 'yes',
      price: 36030,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID4/Volkswagen_ID4-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1411/Volkswagen-ID4-Pure-Performance',
    },
    {
      name: 'Hyundai IONIQ 5 Standard Range 2WD',
      range: 195,
      rapid: 'yes',
      price: 36995,
      img: 'https://ev-database.uk/img/auto/Hyundai_IONIQ5_2021/Hyundai_IONIQ5_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1476/Hyundai-IONIQ-5-Standard-Range-2WD',
    },
    {
      name: 'Kia Soul EV 64kWh',
      range: 225,
      rapid: 'yes',
      price: 37545,
      img: 'https://ev-database.uk/img/auto/Kia_e-Soul/Kia_e-Soul-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1154/Kia-Soul-EV-64-kWh',
    },
    {
      name: 'Volkwagen ID.3 Pro S',
      range: 280,
      rapid: 'yes',
      price: 38800,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID3/Volkswagen_ID3-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1203/Volkswagen-ID3-Pro-S',
    },
    {
      name: 'Skoda Enyaq iV 80',
      range: 260,
      rapid: 'yes',
      price: 39350,
      img: 'https://ev-database.uk/img/auto/Skoda_Enyaq_iV_2020/Skoda_Enyaq_iV_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1280/Skoda-Enyaq-iV-80',
    },
    {
      name: 'Polestar 2 Standard Range Single Motor (coming soon)',
      range: 215,
      rapid: 'yes',
      price: 39900,
      img: 'https://ev-database.uk/img/auto/Polestar_2_2022/Polestar_2_2022-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1486/Polestar-2-Standard-Range-Single-Motor',
    },
    {
      name: 'Nissan Ariya 63kWh (from 2022)',
      range: 205,
      rapid: 'yes',
      price: 40000,
      img: 'https://ev-database.uk/img/auto/Nissan_Ariya/Nissan_Ariya-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1301/Nissan-Ariya-63kWh',
    },
    {
      name: 'Audi Q4 e-tron 35',
      range: 175,
      rapid: 'yes',
      price: 40750,
      img: 'https://ev-database.uk/img/auto/Audi_Q4_e-tron_2021/Audi_Q4_e-tron_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1179/Audi-Q4-e-tron-35',
    },
    {
      name: 'Volkwagen ID.4 1st',
      range: 255,
      rapid: 'yes',
      price: 40800,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID4/Volkswagen_ID4-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1273/Volkswagen-ID4-1st',
    },
    {
      name: 'Kia EV6 Standard Range 2WD (coming soon)',
      range: 200,
      rapid: 'yes',
      price: 40985,
      img: 'https://ev-database.uk/img/auto/Kia_EV6_2021/Kia_EV6_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1480/Kia-EV6-Standard-Range-2WD',
    },
    {
      name: 'Tesla Model 3 Standard Range Plus',
      range: 210,
      rapid: 'yes',
      price: 40990,
      img: 'https://ev-database.uk/img/auto/Tesla_Model_3_2021/Tesla_Model_3_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1485/Tesla-Model-3-Standard-Range-Plus',
    },
    {
      name: 'Ford Mustang Mach-E SR RWD',
      range: 215,
      rapid: 'yes',
      price: 41330,
      img: 'https://ev-database.uk/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1242/Ford-Mustang-Mach-E-SR-RWD',
    },
    {
      name: 'Volkwagen ID.4 Pro Performance',
      range: 255,
      rapid: 'yes',
      price: 41570,
      img: 'https://ev-database.uk/img/auto/Volkswagen_ID4/Volkswagen_ID4-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1314/Volkswagen-ID4-Pro-Performance',
    },
    {
      name: 'Hyundai IONIQ 5 Long Range 2WD (coming soon)',
      range: 240,
      rapid: 'yes',
      price: 41945,
      img: 'https://ev-database.uk/img/auto/Hyundai_IONIQ5_2021/Hyundai_IONIQ5_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1478/Hyundai-IONIQ-5-Long-Range-2WD',
    },
    {
      name: 'Skoda Enyaw iV 80X (coming soon)',
      range: 250,
      rapid: 'yes',
      price: 42000,
      img: 'https://ev-database.uk/img/auto/Skoda_Enyaq_iV_2020/Skoda_Enyaq_iV_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1281/Skoda-Enyaq-iV-80X',
    },
    {
      name: 'CUPRA Born 170kw - 82kWh (from 2022)',
      range: 280,
      rapid: 'yes',
      price: 42000,
      img: 'https://ev-database.uk/img/auto/Cupra_el-Born/Cupra_el-Born-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1518/CUPRA-Born-170-kW---82-kWh',
    },
    {
      name: 'Audi Q4 Sportback e-tron 35',
      range: 180,
      rapid: 'yes',
      price: 42250,
      img: 'https://ev-database.uk/img/auto/Audi_Q4_e-tron_Sportback_2021/Audi_Q4_e-tron_Sportback_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1290/Audi-Q4-Sportback-e-tron-35',
    },
    {
      name: 'Polestar 2 Long Range Single Motor (coming soon)',
      range: 265,
      rapid: 'yes',
      price: 42900,
      img: 'https://ev-database.uk/img/auto/Polestar_2_2022/Polestar_2_2022-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1487/Polestar-2-Long-Range-Single-Motor',
    },
    {
      name: 'Mercedes EQA 250',
      range: 220,
      rapid: 'yes',
      price: 43495,
      img: 'https://ev-database.uk/img/auto/Mercedes_EQA/Mercedes_EQA-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1147/Mercedes-EQA-250',
    },
    {
      name: 'Lexus UX 300e',
      range: 160,
      rapid: 'yes',
      price: 43900,
      img: 'https://ev-database.uk/img/auto/Lexus_UX_300e_Electric_2020/Lexus_UX_300e_Electric_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1251/Lexus-UX-300e',
    },
    {
      name: 'Audi Q4 e-tron 40',
      range: 250,
      rapid: 'yes',
      price: 44990,
      img: 'https://ev-database.uk/img/auto/Audi_Q4_e-tron_2021/Audi_Q4_e-tron_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/img/auto/Audi_Q4_e-tron_2021/Audi_Q4_e-tron_2021-01-thumb.jpg',
    },
    {
      name: 'Nissan Ariya e-4ORCE 63kWh (from 2022)',
      range: 200,
      rapid: 'yes',
      price: 45000,
      img: 'https://ev-database.uk/img/auto/Nissan_Ariya/Nissan_Ariya-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1303/Nissan-Ariya-e-4ORCE-63kWh',
    },
    {
      name: 'Skoda Enyaq iV RS (coming soon)',
      range: 245,
      rapid: 'yes',
      price: 45000,
      img: 'https://ev-database.uk/img/auto/Skoda_Enyaq_iV_2020/Skoda_Enyaq_iV_2020-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1282/Skoda-Enyaq-iV-RS',
    },
    {
      name: 'Nissan Ariya 87kWh (from 2022)',
      range: 275,
      rapid: 'yes',
      price: 45000,
      img: 'https://ev-database.uk/img/auto/Nissan_Ariya/Nissan_Ariya-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1302/Nissan-Ariya-87kWh',
    },
    {
      name: 'Hyundai IONIQ 5 Long Range AWD',
      range: 235,
      rapid: 'yes',
      price: 45145,
      img: 'https://ev-database.uk/img/auto/Hyundai_IONIQ5_2021/Hyundai_IONIQ5_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1479/Hyundai-IONIQ-5-Long-Range-AWD',
    },
    {
      name: 'Polestar 2 Long Range Dual Motor (coming soon)',
      range: 245,
      rapid: 'yes',
      price: 45900,
      img: 'https://ev-database.uk/img/auto/Polestar_2_2022/Polestar_2_2022-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1488/Polestar-2-Long-Range-Dual-Motor',
    },
    {
      name: 'Ford Mustang Mach-E SR AWD',
      range: 205,
      rapid: 'yes',
      price: 46650,
      img: 'https://ev-database.uk/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1244/Ford-Mustang-Mach-E-SR-AWD',
    },
    {
      name: 'Kia EV6 Long Range 2WD (coming soon)',
      range: 260,
      rapid: 'yes',
      price: 48000,
      img: 'https://ev-database.uk/img/auto/Kia_EV6_2021/Kia_EV6_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1481/Kia-EV6-Long-Range-2WD',
    },
    {
      name: 'Hyundai IONIQ 5 Project 45',
      range: 230,
      rapid: 'yes',
      price: 48000,
      img: 'https://ev-database.uk/img/auto/Hyundai_IONIQ5_2021/Hyundai_IONIQ5_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1381/Hyundai-IONIQ-5-Project-45',
    },
    {
      name: 'Tesla Model 3 Long Range Dual Motor',
      range: 280,
      rapid: 'yes',
      price: 48490,
      img: 'https://ev-database.uk/img/auto/Tesla_Model_3_2021/Tesla_Model_3_2021-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1321/Tesla-Model-3-Long-Range-Dual-Motor',
    },
    {
      name: 'Peugeot e-Traveller Standard 50kWh',
      range: 115,
      rapid: 'yes',
      price: 49065,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-Traveller/Peugeot_e-Traveller-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1351/Peugeot-e-Traveller-Standard-50-kWh',
    },
    {
      name: 'Vauxhall Vivaro-e Life Elite L 50 kWh',
      range: 110,
      rapid: 'yes',
      price: 49465,
      img: 'https://ev-database.uk/img/auto/Opel_Zafira-e_Life/Opel_Zafira-e_Life-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1347/Vauxhall-Vivaro-e-Life-Elite-L-50-kWh',
    },
    {
      name: 'Peugeot e-Traveller Long 50kWh',
      range: 115,
      rapid: 'yes',
      price: 49905,
      img: 'https://ev-database.uk/img/auto/Peugeot_e-Traveller/Peugeot_e-Traveller-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1352/Peugeot-e-Traveller-Long-50-kWh',
    },
    {
      name: 'Volco XC40 Recharge Pure Electric',
      range: 210,
      rapid: 'yes',
      price: 49950,
      img: 'https://ev-database.uk/img/auto/Volvo_XC40_Recharge/Volvo_XC40_Recharge-01-thumb.jpg',
      link: 'https://ev-database.uk/car/1520/Volvo-XC40-Recharge-Pure-Electric',
    },
  ];
}

export default carList;
